reFactorial/src/main/resources/templates/imwook.html
=> [2024/11/29] test

reFactorial/src/main/java/com/ohgiraffers/refactorial/approval/controller/ApprovalController.java
=> merge test

reFactorial/src/main/resources/static/header/header.css
=> 241205 css update

reFactorial/src/main/java/com/ohgiraffers/refactorial/MainController.java, reFactorial/src/main/resources/templates/board.html, reFactorial/src/main/resources/templates/common/header.html
=> [1205] test

reFactorial/src/main/resources/templates/approvalMain.html
=> 2024-12-06 문정현 [홈작업 합치기]

reFactorial/src/main/java/com/ohgiraffers/refactorial/config/SecurityConfig.java, reFactorial/src/main/resources/templates/common/header.html
=> 임시 security

reFactorial/src/main/java/com/ohgiraffers/refactorial/board/controller/BoardController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/model/dao/BoardMapper.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/model/dto/BoardDTO.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/service/BoardService.java, reFactorial/src/main/resources/mappers/board/BoardMapper.xml, reFactorial/src/main/resources/templates/board/freeBoardRegist.html, reFactorial/src/main/resources/templates/common/header.html
=> [1209] board_regist

reFactorial/src/main/java/com/ohgiraffers/refactorial/board/controller/BoardController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/model/dao/BoardMapper.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/service/BoardService.java, reFactorial/src/main/resources/mappers/board/BoardMapper.xml, reFactorial/src/main/resources/templates/board/freeBoard.html, reFactorial/src/main/resources/templates/board/postDetail.html, reFactorial/src/main/resources/templates/board/postUpdate.html
=> Feature/121_ board_regist_wook

reFactorial/src/main/java/com/ohgiraffers/refactorial/booking/controller/ReservationController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/booking/model/dao/ReservationDAO.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/booking/service/ReservationService.java
=> [2024-12-11] 삽입

reFactorial/src/main/java/com/ohgiraffers/refactorial/MainController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/booking/controller/ReservationController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/booking/model/dao/ReservationDAO.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/booking/service/ReservationService.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/mail/controller/MailController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/mail/model/dao/MailDAO.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/mail/model/dto/MailDTO.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/mail/service/MailService.java, reFactorial/src/main/resources/mappers/booking/ReservationMapper.xml, reFactorial/src/main/resources/templates/board/document.html, reFactorial/src/main/resources/templates/booking/booking.html, reFactorial/src/main/resources/templates/booking/bookingForm.html, reFactorial/src/main/resources/templates/inquiry/inquiry.html
=> Feature/241212 chan 회의실백엔드 예약/삭제/중복방지

reFactorial/src/main/java/com/ohgiraffers/refactorial/CommonController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/ReFactorialApplication.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/auth/controller/EmailConfirmController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/auth/service/EmailConfirmService.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/config/AuthSuccessHandler.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/user/controller/UserController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/user/model/service/MemberService.java, reFactorial/src/main/resources/templates/myPage/myPage.html
조그마한 오류가 발생하길래 고쳐뒀습니다!
어떤 변경 사항이 있나요?
위에 방식으로 진행하셔야 합니다.
아래방식은 오류 발생!!
=> little error resolve

reFactorial/src/main/java/com/ohgiraffers/refactorial/board/controller/BoardController.java, reFactorial/src/main/resources/static/css/board/freeBoardRegist.css, reFactorial/src/main/resources/templates/board/freeBoardRegist.html, reFactorial/src/main/resources/templates/board/postDetail.html
- 투표기능 연동
- 항목 추가 기능 완성
어떤 변경 사항이 있나요?
=> Feature/1213_board_vote_regist [투표기능]

reFactorial/src/main/resources/templates/board/freeBoardRegist.html
=> merge_resolve [충돌 해결]

reFactorial/src/main/resources/static/css/board/freeBoardRegist.css, reFactorial/src/main/resources/templates/board/freeBoardRegist.html
게시물 등록 페이지 css수정
어떤 변경 사항이 있나요?
=> freeboard css update

reFactorial/src/main/java/com/ohgiraffers/refactorial/approval/service/ApprovalService.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/attendance/controller/AttendanceController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/attendance/dao/AttendanceMapper.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/attendance/service/AttendanceService.java, reFactorial/src/main/resources/mappers/attendance/AtendanceMapper.xml, reFactorial/src/main/resources/static/css/myPage/myPage.css, reFactorial/src/main/resources/templates/index.html, reFactorial/src/main/resources/templates/myPage/myPage.html
=> link calender and attendance [개인 근태와 캘린더 연결]

reFactorial/src/main/java/com/ohgiraffers/refactorial/approval/model/dao/ApprovalMapper.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/approval/model/dao/EmployeeMapper.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/approval/model/dto/DocumentDTO.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/approval/service/ApprovalService.java, reFactorial/src/main/resources/application.yml, reFactorial/src/main/resources/mappers/approval/ApprovalMapper.xml, reFactorial/src/main/resources/mappers/approval/EmployeeMapper.xml, reFactorial/src/main/resources/templates/approvals/Detail.html
결제승인 디테일페이지 ing...
어떤 변경 사항이 있나요?
=> 24/12/16 [결제승인 디테일페이지 ing..]

reFactorial/src/main/java/com/ohgiraffers/refactorial/admin/controller/AdminController.java, reFactorial/src/main/resources/static/css/admin/admin_employee.css, reFactorial/src/main/resources/templates/admin/admin_employee.html
=> re merge [merge 충돌 잡기]

reFactorial/src/main/java/com/ohgiraffers/refactorial/admin/controller/AdminController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/admin/model/dao/AdminMapper.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/admin/model/service/AdminService.java, reFactorial/src/main/resources/mappers/admin/AdminMapper.xml, reFactorial/src/main/resources/static/css/admin/addEmployee.css, reFactorial/src/main/resources/static/css/admin/admin_employee.css, reFactorial/src/main/resources/templates/admin/admin_employee.html
#189 
관리자 페이지에서 사원의 특정 날짜 근태 수정 완료
어떤 변경 사항이 있나요?
=> modify attendance done [관리자 사원 근태 수정 완료]

reFactorial/src/main/java/com/ohgiraffers/refactorial/approval/controller/ApprovalController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/approval/model/dao/ApprovalMapper.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/approval/model/dto/FileDTO.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/approval/service/ApprovalService.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/config/WebConfig.java, reFactorial/src/main/resources/mappers/approval/ApprovalMapper.xml, reFactorial/src/main/resources/mappers/approval/EmployeeMapper.xml, reFactorial/src/main/resources/static/css/approval/Detail.css, reFactorial/src/main/resources/static/css/approval/waiting.css, reFactorial/src/main/resources/templates/approvals/Detail.html, reFactorial/src/main/resources/templates/approvals/approvalMain.html, reFactorial/src/main/resources/templates/approvals/canceled.html, reFactorial/src/main/resources/templates/approvals/completed.html, reFactorial/src/main/resources/templates/approvals/inProgress.html, reFactorial/src/main/resources/templates/approvals/myDocuments.html, reFactorial/src/main/resources/templates/approvals/referenceDocuments.html, reFactorial/src/main/resources/templates/approvals/rejected.html, reFactorial/src/main/resources/templates/approvals/waiting.html
결제 대기중페이지 글 목록 정렬완료
어떤 변경 사항이 있나요?
=> Feature/241217 moon home [결제 대기중페이지 글 목록 정렬]

reFactorial/src/main/java/com/ohgiraffers/refactorial/user/model/service/MemberService.java, reFactorial/src/main/resources/mappers/user/UserMapper.xml, reFactorial/src/main/resources/static/css/mainPage/mainPage.css, reFactorial/src/main/resources/static/css/myPage/myPage.css, reFactorial/src/main/resources/static/js/mainPage/mainPage.js, reFactorial/src/main/resources/templates/index.html
#195 
메인 페이지 디자인 수정
어떤 변경 사항이 있나요?
=> edit mainpage [메인 페이지 수정]

reFactorial/src/main/java/com/ohgiraffers/refactorial/booking/controller/ReservationController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/booking/service/ReservationService.java, reFactorial/src/main/resources/templates/booking/bookingForm.html, reFactorial/src/main/resources/templates/booking/bookingList.html
=> Feature/241217 chan 회의실기능

reFactorial/src/main/java/com/ohgiraffers/refactorial/approval/controller/ApprovalController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/approval/model/dao/ApprovalMapper.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/approval/service/ApprovalService.java, reFactorial/src/main/resources/mappers/approval/ApprovalMapper.xml, reFactorial/src/main/resources/static/css/approval/approvalPage.css, reFactorial/src/main/resources/static/css/approval/completed.css, reFactorial/src/main/resources/static/css/approval/detail.css, reFactorial/src/main/resources/static/css/approval/inProgress.css, reFactorial/src/main/resources/static/css/approval/rejected.css, reFactorial/src/main/resources/templates/approvals/approvalPage.html, reFactorial/src/main/resources/templates/approvals/completed.html, reFactorial/src/main/resources/templates/approvals/detail.html, reFactorial/src/main/resources/templates/approvals/inProgress.html, reFactorial/src/main/resources/templates/approvals/rejected.html, reFactorial/src/main/resources/templates/approvals/waiting.html
결제신청페이지 UI컨셉수정 
결제승인버튼 ing...
어떤 변경 사항이 있나요?
=> Feature/241218 moom home [결제신청페이지 UI컨셉수정 & 결제승인버튼기능 ing..]

reFactorial/src/main/java/com/ohgiraffers/refactorial/board/controller/BoardController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/model/dao/BoardMapper.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/service/BoardService.java, reFactorial/src/main/resources/mappers/board/BoardMapper.xml
=> Feature/1213_board [투표기능]

reFactorial/src/main/java/com/ohgiraffers/refactorial/board/controller/BoardController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/model/dao/BoardMapper.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/model/dto/VoteItemDTO.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/service/BoardService.java, reFactorial/src/main/resources/mappers/board/BoardMapper.xml, reFactorial/src/main/resources/static/css/board/postDetail.css, reFactorial/src/main/resources/templates/board/postDetail.html
#231 
- 투표 DB연결
- 투표 기능
어떤 변경 사항이 있나요?
=> [1219] board_vote [투표기능]

reFactorial/src/main/java/com/ohgiraffers/refactorial/board/controller/BoardController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/model/dao/BoardMapper.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/model/dto/VoteResultDTO.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/service/BoardService.java, reFactorial/src/main/resources/mappers/board/BoardMapper.xml, reFactorial/src/main/resources/templates/board/freeBoardRegist.html, reFactorial/src/main/resources/templates/board/list.html, reFactorial/src/main/resources/templates/board/postDetail.html
- 투표 항목 DB저장
- 투표 결과 DB저장
어떤 변경 사항이 있나요?
=> [1220] board_vote [투표 항목 DB저장, 투표 결과 DB저장]

reFactorial/src/main/java/com/ohgiraffers/refactorial/board/controller/BoardController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/model/dao/BoardMapper.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/model/dto/VoteResultDTO.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/service/BoardService.java, reFactorial/src/main/resources/mappers/board/BoardMapper.xml, reFactorial/src/main/resources/templates/board/postDetail.html, reFactorial/src/main/resources/templates/board/vote.html
=> [1220] board_vote [투표결과 화면 출력]

reFactorial/src/main/java/com/ohgiraffers/refactorial/board/controller/BoardController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/model/dao/BoardMapper.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/service/BoardService.java, reFactorial/src/main/resources/mappers/board/BoardMapper.xml, reFactorial/src/main/resources/templates/board/postDetail.html
=> [1220] board_vote [투표 결과 화면띄우기 진행중]

reFactorial/src/main/java/com/ohgiraffers/refactorial/board/controller/BoardController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/model/dao/BoardMapper.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/model/dto/BoardLikeDTO.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/model/dto/VoteItemDTO.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/model/dto/VoteTotalDTO.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/service/BoardService.java, reFactorial/src/main/resources/mappers/board/BoardMapper.xml, reFactorial/src/main/resources/templates/board/freeBoardRegist.html, reFactorial/src/main/resources/templates/board/postDetail.html
- 총 투표 수
- 투표한 사람 체크
어떤 변경 사항이 있나요?
=> Feature/1213_board_vote[총투표수 + 투표한 사람]

reFactorial/src/main/java/com/ohgiraffers/refactorial/booking/controller/ReservationController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/booking/model/dao/ReservationMapper.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/booking/model/dto/ReservationDTO.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/booking/service/ReservationService.java, reFactorial/src/main/resources/application.yml, reFactorial/src/main/resources/mappers/booking/ReservationMapper.xml, reFactorial/src/main/resources/static/css/booking/booking.css, reFactorial/src/main/resources/static/css/booking/bookingFrom.css, reFactorial/src/main/resources/static/js/booking/booking.js, reFactorial/src/main/resources/templates/board/sidebar.html, reFactorial/src/main/resources/templates/booking/booking.html, reFactorial/src/main/resources/templates/booking/bookingForm.html
#252 
예약 페이지 프론트 작업 & 예약하기 기능 및 예약 불가 시간 막기
어떤 변경 사항이 있나요?
=> create booking page [예약 페이지 프론트 작업 & 예약하기 기능 및 예약 불가 시간 막기]

reFactorial/src/main/java/com/ohgiraffers/refactorial/booking/controller/CabinetController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/booking/controller/ReservationController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/booking/model/dao/ReservationMapper.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/booking/service/ReservationService.java, reFactorial/src/main/resources/mappers/booking/ReservationMapper.xml, reFactorial/src/main/resources/static/css/booking/bookingFrom.css, reFactorial/src/main/resources/static/css/booking/myBookingList.css, reFactorial/src/main/resources/static/js/booking/booking.js, reFactorial/src/main/resources/static/js/booking/myBookingList.js, reFactorial/src/main/resources/templates/booking/booking.html, reFactorial/src/main/resources/templates/booking/bookingForm.html, reFactorial/src/main/resources/templates/booking/myBookingList.html
#257 
예약 페이지 완료
예약하기 완료, 예약 취소 완료, 예약 중복 방지 완료, 나의 예약 내역 가져오기 완료
어떤 변경 사항이 있나요?
=> Feature/booking done yejin [예약 페이지 완료]

reFactorial/src/main/resources/static/css/sharedWork/sharedWork.css, reFactorial/src/main/resources/templates/sharedWork/allWork.html
#259 
- 업무공유 일정추가 기능
어떤 변경 사항이 있나요?
=> [1223] sharedWork [업무공유/일정추가]

reFactorial/src/main/resources/templates/mail/mailMain.html, reFactorial/src/main/resources/templates/mail/receivedMails.html, reFactorial/src/main/resources/templates/mail/replyMail.html, reFactorial/src/main/resources/templates/mail/sendMail.html, reFactorial/src/main/resources/templates/mail/sentMails.html
=> [241224] chan_mail_html

reFactorial/src/main/java/com/ohgiraffers/refactorial/sharedWork/controller/SharedWorkController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/sharedWork/model/dto/SharedWorkDTO.java, reFactorial/src/main/resources/templates/sharedWork/allWork.html
#262
- 업무공유 캘린더 속성 추가
어떤 변경 사항이 있나요?
=> Shard work/1223 [업무공유]

reFactorial/src/main/java/com/ohgiraffers/refactorial/MainController.java
관리자페이지 안들어가지는 오류 maincontroller 수정완료
어떤 변경 사항이 있나요?
=> 24/12/26 [관리자페이지 안들어가지는 오류 maincontroller 수정완료]

reFactorial/src/main/java/com/ohgiraffers/refactorial/auth/service/AuthService.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/sharedWork/controller/SharedWorkController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/sharedWork/model/dao/SharedWorkMapper.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/sharedWork/model/dto/SharedWorkDTO.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/sharedWork/service/SharedWorkService.java, reFactorial/src/main/resources/mappers/sharedWork/sharedWorkMappler.xml, reFactorial/src/main/resources/templates/sharedWork/allWork.html
#278 
- 일정 db저장 완료 
-  조회 기능 진행
어떤 변경 사항이 있나요?
=> [1226] sharedWork [일정 db저장 완료 / 조회 기능 진행]

reFactorial/src/main/java/com/ohgiraffers/refactorial/sharedWork/controller/SharedWorkController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/sharedWork/model/dao/SharedWorkMapper.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/sharedWork/service/SharedWorkService.java, reFactorial/src/main/resources/mappers/sharedWork/sharedWorkMappler.xml, reFactorial/src/main/resources/templates/sharedWork/allWork.html
- 업무공유 조회, 등록, 수정, 삭제 완료
어떤 변경 사항이 있나요?
=> Shard work/1223 [업무공유 조회,등록,수정,삭제 완료]

reFactorial/src/main/java/com/ohgiraffers/refactorial/board/controller/BoardController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/model/dto/BoardDTO.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/service/BoardService.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/config/WebConfig.java, reFactorial/src/main/resources/static/css/board/postDetail.css, reFactorial/src/main/resources/templates/board/postDetail.html
#294 
- 페이지네이션 진행
어떤 변경 사항이 있나요?
=> Daily work [페이지네이션 진행중]

reFactorial/src/main/java/com/ohgiraffers/refactorial/MainController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/admin/controller/AdminController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/admin/model/dao/AdminMapper.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/admin/model/service/AdminService.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/approval/controller/ApprovalController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/approval/model/dao/ApprovalMapper.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/approval/service/ApprovalService.java, reFactorial/src/main/resources/mappers/admin/AdminMapper.xml, reFactorial/src/main/resources/mappers/approval/ApprovalMapper.xml, reFactorial/src/main/resources/static/css/admin/admin_factoryAddressBook.css, reFactorial/src/main/resources/templates/addressBook/factory.html, reFactorial/src/main/resources/templates/admin/admin_factoryAddressBook.html
[24/12/27 [메인컨트롤 예외처리 ]
[24/12/28 [관리자페이지 업체수정하기 완료]
[24/12/28 [전자결제 휴가신청서 날짜 근태와 연결완료]
어떤 변경 사항이 있나요?
=> Feature/241228 moon home [ 자세한내용은들어와서 봐주시면감사하겠습니다!]

reFactorial/src/main/java/com/ohgiraffers/refactorial/auth/service/EmailConfirmService.java, reFactorial/src/main/resources/mappers/user/UserMapper.xml, reFactorial/src/main/resources/static/css/admin/addEmployee.css, reFactorial/src/main/resources/static/css/admin/common/admin_circleBtn.css, reFactorial/src/main/resources/static/css/myPage/myPage.css, reFactorial/src/main/resources/static/js/admin/addEmployee.js, reFactorial/src/main/resources/static/js/admin/admin_employee.js, reFactorial/src/main/resources/static/js/myPage/myPage.js, reFactorial/src/main/resources/templates/admin/addEmployee.html, reFactorial/src/main/resources/templates/admin/admin_main.html, reFactorial/src/main/resources/templates/auth/login.html, reFactorial/src/main/resources/templates/index.html, reFactorial/src/main/resources/templates/myPage/myPage.html
#308 
차트 정렬 맞추기(날짜 기준)
예외처리 required 추가 및 이메일, 비밀번호, 전화번호, 주민번호 유효성 검사 넣기
초기 비밀번호 생년월일로 설정
인증 이메일 사용자 이메이로 연결
어떤 변경 사항이 있나요?
=> setting required [예외처리 및 기타 세팅]

reFactorial/src/main/resources/static/css/loginPage/loginPage.css
=> css update [빠진 파일 반영]

reFactorial/src/main/java/com/ohgiraffers/refactorial/MainController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/controller/BoardController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/model/dao/BoardMapper.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/model/dto/BoardDTO.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/service/BoardService.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/sharedWork/controller/SharedWorkController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/sharedWork/model/dto/SharedWorkDTO.java, reFactorial/src/main/resources/mappers/board/BoardMapper.xml, reFactorial/src/main/resources/mappers/sharedWork/sharedWorkMappler.xml, reFactorial/src/main/resources/static/css/board/list.css, reFactorial/src/main/resources/templates/board/freeBoardRegist.html, reFactorial/src/main/resources/templates/board/list.html, reFactorial/src/main/resources/templates/common/header.html, reFactorial/src/main/resources/templates/sharedWork/allWork.html
#297 
- 모든 게시판 페이지네이션
- 예외처리 / 리콰이어드 적용 완료
- 투표 / 문서 게시판 직접 등록 시 항목, 첨부파일 안뜨는거 해결
- 게시글 사용자 분류 (유저, 관리자)
- 업무공유 업무 등록 시 각각 색깔 변경
어떤 변경 사항이 있나요?
=> [1229] sharedWork [업무공유 완성, 게시판 수정]

reFactorial/src/main/resources/templates/approvals/approvalMain.html, reFactorial/src/main/resources/templates/approvals/myDocuments.html
[전자결제 결제신청버튼수정]
어떤 변경 사항이 있나요?
=> 24/12/30 [전자결제 결제신청버튼수정]

reFactorial/src/main/java/com/ohgiraffers/refactorial/user/controller/UserController.java, reFactorial/src/main/resources/static/css/mainPage/mainPage.css, reFactorial/src/main/resources/templates/index.html
css 수정 및 조회 구간 수정
어떤 변경 사항이 있나요?
=> check event css update

reFactorial/src/main/java/com/ohgiraffers/refactorial/board/controller/BoardController.java, reFactorial/src/main/resources/templates/board/freeBoardRegist.html
=> [1230] board regist[게시판 오류 수정]

reFactorial/src/main/java/com/ohgiraffers/refactorial/board/controller/BoardController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/model/dao/BoardMapper.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/service/BoardService.java, reFactorial/src/main/resources/mappers/board/BoardMapper.xml, reFactorial/src/main/resources/static/js/board/freeBoardRegist.js, reFactorial/src/main/resources/templates/board/freeBoardRegist.html, reFactorial/src/main/resources/templates/board/postDetail.html
=> [1231] board_end [게시물 투표 수정기능]

reFactorial/src/main/java/com/ohgiraffers/refactorial/board/controller/BoardController.java, reFactorial/src/main/resources/static/js/board/freeBoardRegist.js
=> Feature/1231_board_end[게시글 투표 수정]

reFactorial/src/main/resources/static/css/board/list.css, reFactorial/src/main/resources/templates/board/list.html
용욱님 게시판 CSS오류수정
어떤 변경 사항이 있나요?
=> 25/01/01 [용욱님 게시판 CSS 수정]

reFactorial/src/main/java/com/ohgiraffers/refactorial/approval/controller/ApprovalController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/mail/controller/MailController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/mail/model/dao/MailEmployeeMapper.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/mail/model/dao/MailMapper.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/mail/service/MailEmployeeService.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/mail/service/MailService.java, reFactorial/src/main/resources/mappers/mail/MailEmployeeMapper.xml, reFactorial/src/main/resources/mappers/mail/MailMapper.xml, reFactorial/src/main/resources/static/css/mail/receivedMails.css, reFactorial/src/main/resources/templates/approvals/completed.html, reFactorial/src/main/resources/templates/approvals/inProgress.html, reFactorial/src/main/resources/templates/approvals/myDocuments.html, reFactorial/src/main/resources/templates/approvals/referenceDocuments.html, reFactorial/src/main/resources/templates/approvals/rejected.html, reFactorial/src/main/resources/templates/approvals/waiting.html, reFactorial/src/main/resources/templates/mail/receivedMails.html
승찬님 메일 페이지네이션 기능
어떤 변경 사항이 있나요?
=> Feature/250101 moon home [승찬님 메일 페이지네이션 기능]

reFactorial/src/main/java/com/ohgiraffers/refactorial/MainController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/addressBook/controller/AddressBookController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/approval/service/ApprovalService.java, reFactorial/src/main/resources/static/css/approval/detail.css, reFactorial/src/main/resources/static/css/loginPage/loginPage.css, reFactorial/src/main/resources/static/js/approval/detail.js, reFactorial/src/main/resources/static/js/loginPage/loginPage.js, reFactorial/src/main/resources/templates/auth/login.html
[25/01/01 [sout 지우기완료]]
[25/01/02 [결제상세페이지 모달창 취소버튼 기능 오류수정]]
[25/01/02 [ 로그인 페이지 눈송이 내리기]]
어떤 변경 사항이 있나요?
=> Feature/250102 moon home [sout 지우기 ,모달창오류수정, 로그인페이지 눈내리기]

reFactorial/src/main/java/com/ohgiraffers/refactorial/approval/controller/ApprovalController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/approval/model/dao/ApprovalMapper.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/approval/service/ApprovalService.java, reFactorial/src/main/resources/mappers/approval/ApprovalMapper.xml, reFactorial/src/main/resources/templates/approvals/approvalPage.html
[ 전자결제 반려이유 승인자들에게 전부보이기]
어떤 변경 사항이 있나요?
=> 25/01/02 [ 전자결제 반려이유 승인자들에게 전부보이기]

reFactorial/src/main/java/com/ohgiraffers/refactorial/board/controller/BoardController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/model/dao/BoardMapper.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/board/service/BoardService.java, reFactorial/src/main/resources/mappers/board/BoardMapper.xml, reFactorial/src/main/resources/templates/board/list.html
[게시판 페이지네이션 오류수정]
어떤 변경 사항이 있나요?
=> 25/01/02 [게시판 페이지네이션 오류수정]

reFactorial/src/main/resources/templates/inquiry/adminInquiryAnswerList.html
=> Feature/1231 board end [승찬님 코드수정]

reFactorial/src/main/java/com/ohgiraffers/refactorial/addressBook/controller/AddressBookController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/admin/controller/AdminController.java, reFactorial/src/main/java/com/ohgiraffers/refactorial/admin/model/service/AdminService.java, reFactorial/src/main/resources/static/js/admin/notificationEvent.js, reFactorial/src/main/resources/templates/board/postDetail.html
=> css update
